"""
Pydantic models for quiz question generation.

This module defines the structured output models used when generating
multiple-choice quiz questions via LLM.
"""

from typing import Literal
from pydantic import BaseModel, Field


class QuizQuestion(BaseModel):
    """
    Represents a single multiple-choice quiz question generated by the LLM.
    """
    question_text: str = Field(description="The full text of the multiple-choice question.")
    option_a: str = Field(description="The text for option A.")
    option_b: str = Field(description="The text for option B.")
    option_c: str = Field(description="The text for option C.")
    option_d: str = Field(description="The text for option D.")
    correct_answer: Literal["A", "B", "C", "D"] = Field(
        description="The letter of the correct answer (e.g., 'A', 'B', 'C', 'D')."
    )

